import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ToastContainer } from "react-toastify"
import Header from "@/components/Header";


export const metadata: Metadata = {
  title: "Clinic Dashboard",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}
export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        <main>
          <Navbar />
          <Header />
          <ToastContainer
          position="top-center"
          autoClose={2000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
        />
          {children}
        </main>
      </body>
    </html>
  );
}
